Repository Lap343/poke-app, pull requests merged in 2021-07, with the labels that each got.

#15 feat(pokemon-app):Initialize setup for react app
  pokemon-app/.gitignore
  pokemon-app/README.md
  pokemon-app/package-lock.json
  pokemon-app/package.json
  pokemon-app/public/favicon.ico
  pokemon-app/public/index.html
  pokemon-app/public/logo192.png
  pokemon-app/public/logo512.png
  pokemon-app/public/manifest.json
  pokemon-app/public/robots.txt
  pokemon-app/src/App.css
  pokemon-app/src/App.js
  pokemon-app/src/App.test.js
  pokemon-app/src/index.css
  pokemon-app/src/index.js
  pokemon-app/src/logo.svg
  pokemon-app/src/reportWebVitals.js
  pokemon-app/src/setupTests.js
Labels: enhancement

#16 feat(pokedex-model);Added pokedex model with an opening and closing animations
  .vscode/settings.json
  pokemon-app/public/dex-left.png
  pokemon-app/public/dex-right-close.png
  pokemon-app/public/dex-right-open.png
  pokemon-app/public/favicon.ico
  pokemon-app/public/index.html
  pokemon-app/public/logo192.png
  pokemon-app/public/logo512.png
  pokemon-app/src/App.css
  pokemon-app/src/App.js
  pokemon-app/src/logo.svg
Labels: enhancement

#17 Eg 8 api function calls
  pokemon-app/.gitignore
  pokemon-app/src/App.js
  pokemon-app/src/utils/api.js
Labels: enhancement

#18 Lp 2 pokedex splash screen
  pokemon-app/src/App.css
  pokemon-app/src/App.js
  pokemon-app/src/assets/dex-left.png
  pokemon-app/src/assets/dex-right-close.png
  pokemon-app/src/assets/dex-right-open.png
  pokemon-app/src/assets/splash-background.png
  pokemon-app/src/assets/splash-star.png
  pokemon-app/src/assets/splash-title.png
  pokemon-app/src/components/Main.js
Labels: enhancement

#20 feat(pokedex):Reconfig sizing units for the pokedex app
  pokemon-app/src/App.css
  pokemon-app/src/App.js
Labels: enhancement

#22 Eg 5 searched pokemon evolutions
  pokemon-app/src/App.css
  pokemon-app/src/components/PokemonEvolutions.js
  pokemon-app/src/utils/api.js
Labels: enhancement

#27 feat(pokemon-evolution): change parameter name for getEvolutionChain …
  pokemon-app/src/App.css
  pokemon-app/src/App.js
  pokemon-app/src/utils/api.js
Labels: enhancement

#28 Lp 26 change app font
  pokemon-app/public/manifest.json
  pokemon-app/src/assets/pokeFont.ttf
  pokemon-app/src/components/Main.js
  pokemon-app/src/index.css
Labels: enhancement

#32 bug(pokedex):resize pokedex and main screen
  pokemon-app/src/App.css
  pokemon-app/src/App.js
  pokemon-app/src/assets/fightpad.png
  pokemon-app/src/assets/mainBackground.png
  pokemon-app/src/components/Main.js
  pokemon-app/src/components/PokemonEvolutions.js
  pokemon-app/src/components/Search.js
  pokemon-app/src/components/SinglePokemon.js
  pokemon-app/src/index.css
Labels: bug

#34 Lp 7 type weaknesses and strengths
  pokemon-app/src/App.js
  pokemon-app/src/components/Main.js
  pokemon-app/src/components/SinglePokemon.js
  pokemon-app/src/components/TypeCheck.js
  pokemon-app/src/components/typeMatchups.js
  pokemon-app/src/styles/App.css
  pokemon-app/src/styles/TypeCheck.css
Labels: enhancement

#43 Lp 40 remove Pokémon functionality
  pokemon-app/src/App.js
  pokemon-app/src/components/Search.js
  pokemon-app/src/components/TypeCheck.js
  pokemon-app/src/components/typeMatchups.js
  pokemon-app/src/index.css
  pokemon-app/src/styles/EnemyPokemon.css
  pokemon-app/src/styles/Poke-evolutions.css
  pokemon-app/src/styles/Pokedex-model.css
Labels: bug

#45 feat(pokemon-searchbar):switch form to a controlled logic
  pokemon-app/src/components/Search.js
Labels: enhancement

#47 Eg 9 vs animation
  pokemon-app/src/App.js
  pokemon-app/src/components/Main.js
  pokemon-app/src/components/Search.js
  pokemon-app/src/components/Versus.js
  pokemon-app/src/styles/Versus.css
Labels: enhancement

#51 feat(pokemon): add Reactoad pokemon on 404 from the Api
  pokemon-app/src/App.js
  pokemon-app/src/assets/toad.png
  pokemon-app/src/components/toad.js
  pokemon-app/src/components/typeMatchups.js
  pokemon-app/src/utils/api.js
Labels: enhancement

#54 Eg 42 pokeball animation
  pokemon-app/src/App.js
  pokemon-app/src/components/Main.js
  pokemon-app/src/components/Pokeball.js
  pokemon-app/src/components/Search.js
  pokemon-app/src/styles/Pokeball.css
Labels: enhancement

#55 Lp 36 base pokemon stats
  pokemon-app/src/components/EnemyPokemon.js
  pokemon-app/src/components/SinglePokemon.js
  pokemon-app/src/styles/EnemyPokemon.css
  pokemon-app/src/styles/One-pokemon-page.css
  pokemon-app/src/styles/Poke-evolutions.css
  pokemon-app/src/styles/Pokedex-model.css
  pokemon-app/src/styles/TypeCheck.css
Labels: enhancement

#56 Eg 53 clickable evolutions
  pokemon-app/src/App.js
  pokemon-app/src/components/EnemyPokemon.js
  pokemon-app/src/components/Main.js
  pokemon-app/src/components/PokemonEvolutions.js
  pokemon-app/src/components/SinglePokemon.js
  pokemon-app/src/styles/Poke-evolutions.css
Labels: enhancement

#57 feat(Pokémon-types):add Pokémon types and the switch depending in the Pokémon type
  pokemon-app/src/components/EnemyPokemon.js
  pokemon-app/src/components/PokemonEvolutions.js
  pokemon-app/src/components/SinglePokemon.js
  pokemon-app/src/components/Types.js
  pokemon-app/src/styles/EnemyPokemon.css
  pokemon-app/src/styles/One-pokemon-page.css
  pokemon-app/src/styles/Poke-evolutions.css
  pokemon-app/src/styles/Types.css
Labels: bug, enhancement

#58 fix the search button so it deosn't search on an empty input value
  pokemon-app/src/components/Search.js
Labels: bug

#62 Eg 12 pokemons cry
  pokemon-app/src/assets/sounds/reactoad.mp3
  pokemon-app/src/components/EnemyPokemon.js
  pokemon-app/src/components/Main.js
  pokemon-app/src/components/PokemonCry.js
  pokemon-app/src/components/SinglePokemon.js
  pokemon-app/src/components/ThemeSongs.js
  pokemon-app/src/styles/PokemonCry.css
  pokemon-app/src/utils/pokeCries.js
Labels: enhancement

#63 Lp 50 scaling issues
  pokemon-app/src/App.css
  pokemon-app/src/App.js
  pokemon-app/src/components/SinglePokemon.js
  pokemon-app/src/index.css
  pokemon-app/src/styles/EnemyPokemon.css
  pokemon-app/src/styles/One-pokemon-page.css
  pokemon-app/src/styles/Pokedex-model.css
  pokemon-app/src/styles/TypeCheck.css
Labels: enhancement

#66 feat(two-searched-pokemon-screen): adds labels to user and enemy pokemon
  pokemon-app/src/components/EnemyPokemon.js
  pokemon-app/src/components/SinglePokemon.js
  pokemon-app/src/styles/EnemyPokemon.css
Labels: enhancement

#67 Eg 59 moves list arrow
  pokemon-app/src/components/EnemyPokemon.js
  pokemon-app/src/components/SinglePokemon.js
  pokemon-app/src/hooks/index.js
  pokemon-app/src/hooks/useScroll.js
  pokemon-app/src/styles/EnemyPokemon.css
  pokemon-app/src/styles/One-pokemon-page.css
Labels: enhancement

#71 Eg 68 fix movelists arrows
  pokemon-app/src/components/EnemyPokemon.js
  pokemon-app/src/components/SinglePokemon.js
  pokemon-app/src/styles/EnemyPokemon.css
  pokemon-app/src/styles/One-pokemon-page.css
Labels: bug

#72 feat(moveslist-component): create a MovesList component; style the Mo…
  pokemon-app/src/components/EnemyPokemon.js
  pokemon-app/src/components/MovesList.js
  pokemon-app/src/components/SinglePokemon.js
  pokemon-app/src/styles/EnemyPokemon.css
  pokemon-app/src/styles/MovesList.css
  pokemon-app/src/styles/One-pokemon-page.css
Labels: enhancement
