Repository Lap343/poke-app, pull requests merged in 2021-08, with the labels that each got.

#74 fix(fix-types-capitalize): create a capitalize function in capitalize…
  pokemon-app/src/components/Types.js
  pokemon-app/src/utils/capitalize.js
  pokemon-app/src/utils/index.js
Labels: bug

#75 Jv 69 sound button placement
  pokemon-app/src/assets/volIcon2.png
  pokemon-app/src/components/Search.js
  pokemon-app/src/components/ThemeSongs.js
  pokemon-app/src/styles/ThemeSongs.css
Labels: bug

#76 Autoplay Bug for iOS Users
  pokemon-app/src/App.js
  pokemon-app/src/components/EnemyPokemon.js
  pokemon-app/src/components/Main.js
  pokemon-app/src/components/PokemonCry.js
  pokemon-app/src/components/Search.js
  pokemon-app/src/components/SinglePokemon.js
  pokemon-app/src/utils/api.js
  pokemon-app/src/utils/audioPlayAsync.js
  pokemon-app/src/utils/index.js
Labels: bug

#80 Eg 77 effectiveness label moves
  pokemon-app/src/App.js
  pokemon-app/src/components/EnemyPokemon.js
  pokemon-app/src/components/Main.js
  pokemon-app/src/components/MovesList.js
  pokemon-app/src/components/toad.js
  pokemon-app/src/components/typeMatchups.js
  pokemon-app/src/utils/api.js
Labels: enhancement

#83 Lp 79 zoom in animation
  pokemon-app/src/App.css
  pokemon-app/src/styles/Pokedex-model-mobile.css
  pokemon-app/src/styles/Pokedex-model.css
Labels: enhancement

#85 Lp 84 mute button fix
  pokemon-app/src/components/Search.js
  pokemon-app/src/components/ThemeSongs.js
Labels: bug

#87 Jv 81 style effectiveness label
  pokemon-app/src/components/MovesList.js
  pokemon-app/src/styles/MovesList.css
Labels: enhancement

#88 Eg 82 overall effectiveness
  pokemon-app/src/App.js
  pokemon-app/src/components/EnemyPokemon.js
  pokemon-app/src/components/Main.js
  pokemon-app/src/components/MovesList.js
  pokemon-app/src/components/SinglePokemon.js
  pokemon-app/src/styles/MovesList.css
  pokemon-app/src/utils/effectiveness.js
Labels: enhancement

#94 Eg 92 attacker defender title
  pokemon-app/src/components/EnemyPokemon.js
  pokemon-app/src/components/SinglePokemon.js
  pokemon-app/src/styles/EnemyPokemon-mobile.css
  pokemon-app/src/styles/EnemyPokemon.css
Labels: enhancement

#95 fix(type-capitalization): capitalize the type value with the capitali…
  pokemon-app/src/components/TypeCheck.js
Labels: bug

#96 fix(evolutions-scrollbar): increase the width of the border, and decr…
  pokemon-app/src/styles/Poke-evolutions.css
Labels: bug

#98 fix(type-scrollbar): increase the border properties for type-title, t…
  pokemon-app/src/styles/TypeCheck.css
Labels: bug

#100 Jv 89 make labels mobile
  pokemon-app/src/styles/EnemyPokemon-mobile.css
  pokemon-app/src/styles/MovesList.css
  pokemon-app/src/styles/One-pokemon-page-mobile.css
Labels: enhancement

#102 Eg 99 fix console warnings
  pokemon-app/src/App.js
  pokemon-app/src/components/Main.js
  pokemon-app/src/components/Search.js
  pokemon-app/src/components/ThemeSongs.js
  pokemon-app/src/components/Versus.js
  pokemon-app/src/styles/Pokedex-model-mobile.css
  pokemon-app/src/styles/ThemeSongs.css
Labels: bug

#104 Custom Audio Hook
  pokemon-app/src/components/PokemonCry.js
  pokemon-app/src/components/ThemeSongs.js
  pokemon-app/src/hooks/index.js
  pokemon-app/src/hooks/useAudio.js
Labels: enhancement

#105 Expand Effectiveness Points
  pokemon-app/src/components/typeMatchups.js
  pokemon-app/src/styles/MovesList.css
  pokemon-app/src/utils/effectiveness.js
Labels: enhancement

#108 Moves Game
  pokemon-app/src/App.js
  pokemon-app/src/components/EnemyPokemon.js
  pokemon-app/src/components/Main.js
  pokemon-app/src/components/MovesList.js
  pokemon-app/src/components/ProgressBar.js
  pokemon-app/src/components/Search.js
  pokemon-app/src/components/SinglePokemon.js
  pokemon-app/src/components/toad.js
  pokemon-app/src/styles/MovesList.css
  pokemon-app/src/styles/ProgressBar-mobile.css
  pokemon-app/src/styles/ProgressBar.css
  pokemon-app/src/utils/api.js
  pokemon-app/src/utils/effectiveness.js
  pokemon-app/src/utils/index.js
  pokemon-app/src/utils/randomGenerator.js
  pokemon-app/src/utils/updateHPStats.js
Labels: enhancement

#111 Implement onKeyDown
  pokemon-app/src/components/Search.js
Labels: enhancement

#110 doc(pokedex-app):add a readme
  README.md
  pokemon-app/src/assets/forReadMe/HalfDamage.png
  pokemon-app/src/assets/forReadMe/HealthBar.png
  pokemon-app/src/assets/forReadMe/Ineffective.png
  pokemon-app/src/assets/forReadMe/MainOneThird.png
  pokemon-app/src/assets/forReadMe/MainScreen.png
  pokemon-app/src/assets/forReadMe/MainThreeThirds.png
  pokemon-app/src/assets/forReadMe/MainTwoThirds.png
  pokemon-app/src/assets/forReadMe/Moves&StatsTabs.png
  pokemon-app/src/assets/forReadMe/MuteButton.png
  pokemon-app/src/assets/forReadMe/RemovePokemonButton.png
  pokemon-app/src/assets/forReadMe/SearchBar.png
  pokemon-app/src/assets/forReadMe/SplashScreen.png
  pokemon-app/src/assets/forReadMe/SuperEffective.png
  pokemon-app/src/assets/forReadMe/VsScreen.png
  pokemon-app/src/assets/forReadMe/Yours&EnemysPokemonButtons.png
  pokemon-app/src/components/TypeCheck.js
Labels: documentation

#112 Jv 101 credits screen
  pokemon-app/src/App.js
  pokemon-app/src/assets/bulbasaur-pixel-removebg-preview.png
  pokemon-app/src/assets/duck-poke.png
  pokemon-app/src/assets/emolga.gif
  pokemon-app/src/assets/finger-pointing.png
  pokemon-app/src/assets/noctowl-body.png
  pokemon-app/src/assets/noctowl-feet.png
  pokemon-app/src/assets/noctowl-head.png
  pokemon-app/src/assets/sounds/lakeSong.mp3
  pokemon-app/src/assets/wild-poke.png
  pokemon-app/src/components/CreditScreen.js
  pokemon-app/src/components/Main.js
  pokemon-app/src/components/Search.js
  pokemon-app/src/styles/CreditScreen.css
Labels: enhancement

#122 bug(mute-btn):move the mute button off of the search enemy switch
  pokemon-app/.firebase/hosting.YnVpbGQ.cache
  pokemon-app/.firebaserc
  pokemon-app/firebase.json
  pokemon-app/src/styles/One-pokemon-page-mobile.css
  pokemon-app/src/styles/Pokedex-model.css
Labels: bug

#124 Fix Moves Arrows
  pokemon-app/src/styles/EnemyPokemon-mobile.css
  pokemon-app/src/styles/MovesList.css
  pokemon-app/src/styles/One-pokemon-page-mobile.css
Labels: bug

#125 Fix Moves Scroll
  pokemon-app/src/styles/MovesList.css
Labels: bug

#126 Lp 116 mobile vs effectiveness label
  pokemon-app/src/styles/MovesList.css
Labels: bug

#128 Jv 119 credits button placement
  pokemon-app/src/styles/CreditScreen.css
Labels: bug

#129 Lp 127 read me documentation
  README.md
Labels: documentation

#130 bug(pokemon-types):set the Pokémon type to a specific spot on the page when on mobile
  pokemon-app/src/styles/EnemyPokemon-mobile.css
  pokemon-app/src/styles/One-pokemon-page-mobile.css
Labels: bug

#133 Lp 132 mobile scrollbar styling
  pokemon-app/src/styles/One-pokemon-page-mobile.css
Labels: bug

#135 bug(audio):fix audio inconsistencies bug
  pokemon-app/src/components/Main.js
Labels: bug

#136 Jv 131 mobile friendly credits
  pokemon-app/src/styles/CreditScreen.css
Labels: bug

#137 version update after bug fixes
  pokemon-app/package.json
Labels: enhancement
